name: MidiPlayer
main: org.primesoft.midiplayer.MidiPlayerMain
version: {project.version}
website: https://github.com/sgdc3/MidiPlayer
description: A bukkit/spigot plugin that allows you to play midi songs in your server.
authors: [SBPrime, sgdc3]
commands:
  mpreload:
    description: 'Reload the config'
    usage: /<command>
    permission: midiplayer.admin.reload
  playmidi:
    description: 'Play midi file for calling player'
    usage: /<command>
    permission: midiplayer.play
    aliases: play
  playmiditoplayer:
    description: 'Play midi file to a specific player'
    usage: /<command> <song>
    permission: midiplayer.playtoplayer
    aliases: playtoplayer
  playglobalmidi:
    description: 'Play midi file for all players on the server'
    usage: /<command>
    permission: midiplayer.playglobal
    aliases: gplay
permissions:
  musicplayer.*:
    description: Grants access to all MidiPlayer permissions
    default: op
    children:      
      midiplayer.admin.*: true
      midiplayer.playglobal: true
      midiplayer.play: true
      midiplayer.playtoplayer: true
  midiplayer.playglobal:
    description: Grants access to play global midi command
    default: op
  midiplayer.admin.*:
    description: Grants access to all MidiPlayer admin permissions
    default: op
    children:      
      musicplayer.admin.reload: true
  midiplayer.admin.reload:
    description: Allows you to reload MidiPlayer config
    default: op